version: '3.3'
services:
    openmole:
        image: openmole/openmole:latest
        command: openmole-docker --rest --password ""
        # docker run --rm --privileged -p 8080:8080 openmole/openmole:latest     openmole --port 8080 --reset --reset-password --rest --password ""
        ports:
            - ${OPENMOLE_PORT}:${OPENMOLE_PORT}
        privileged: true
        restart: on-failure:100000
    db:
        image: postgres:13.4-buster
        user: postgres
        environment:
            POSTGRES_PASSWORD: pass
            POSTGRES_HOST_AUTH_METHOD: scram-sha-256
            # Needed for database to initialize correctly with an alternative
            # auth method. See https://hub.docker.com/_/postgres/
            POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
        ports:
            - ${DB_PORT}:${DB_PORT}
    backend:
        build:
            context: backend/
            args:
                LOCAL_SRC: ${LOCAL_SRC}
                JOB_REPO_LOCAL: ${JOB_REPO_LOCAL}
                BACKEND_PORT: ${BACKEND_PORT}
        ports:
            - 8888:8888/tcp
        volumes:
            # TESTING
            - /home/guillaume/Work/Dev/2021/AntsDispersalStrategyWebApp/test-job:$JOB_REPO_ORIGIN
        environment:
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            OPENMOLE_HOST: ${OPENMOLE_HOST}
            OPENMOLE_PORT: ${OPENMOLE_PORT}


